### ISSUE TITLE
Create lst files inside script folder not in home

### ISSUE THREAD

**Issue by cptX** [Typr/f2b-nuke#1]
Hi, I'm having all my scripts in a folder ~/scripts.
Inside there I installed the folder f2b-nuke with your script. Then I ran it from there but it created the another folder in home. This isn't very practical. I don't want to mess up my home directory.
So please make the script create the lst files inside the f2b-nuke folder.

By the way very useful script. Saved me a lot of time! Thanks for your good work!

**Comment by joeweller** [comment]
Although this is an issue and can most definitely be de-cluttered, the project is no longer actively maintained, but fire in a PR and will be happy to get this resolved!

Also I am glad this helped you!
